#include <iomanip>
#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <cstdlib>
#include <ctime>
#include <fstream>
#include <chrono>
#include <stdexcept>
#include <sstream>
#include <deque>
#include <list>
#include <numeric>
#include <limits>
#include <exception>
#include <variant>
#include <cassert>

using std::deque;
using std::list;
using std::min;
using std::istringstream;
using std::ostringstream;
using std::stringstream;
using std::cin;
using std::cout;
using std::endl;
using std::string;
using std::vector;
using std::fixed;
using std::setprecision;
using std::sort;
using std::to_string;
using std::rand;
using std::srand;
using std::time;   
using std::copy;
using std::ifstream;
using std::ofstream;
using std::numeric_limits;
using std::streamsize;
using std::ios;
using std::left;
using std::setw;
using std::chrono::high_resolution_clock;
using std::chrono::duration_cast;
using std::chrono::milliseconds; 
using std::chrono::seconds;
using std::runtime_error;
using std::invalid_argument;
using std::cerr;
using std::exception;
using std::move;
using std::accumulate;
using std::max;
using std::is_same;
using std::ostream;
using std::istream;
using std::variant;
