.TH "Catch::Detail::IsStreamInsertable< T >" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Detail::IsStreamInsertable< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBvalue\fP = decltype(test<std::ostream, const T&>(0))::value"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<typename T> const bool \fBCatch::Detail::IsStreamInsertable\fP< T >::value = decltype(test<std::ostream, const T&>(0))::value\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
