.TH "Catch::AutoReg" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::AutoReg
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.PP
Inherits \fBCatch::NonCopyable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAutoReg\fP (\fBITestInvoker\fP *invoker, \fBSourceLineInfo\fP const &lineInfo, \fBStringRef\fP const &classOrMethod, \fBNameAndTags\fP const &nameAndTags) noexcept"
.br
.ti -1c
.RI "\fB~AutoReg\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBCatch::NonCopyable\fP
.in +1c
.ti -1c
.RI "\fBNonCopyable\fP ()"
.br
.ti -1c
.RI "virtual \fB~NonCopyable\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::AutoReg::AutoReg (\fBITestInvoker\fP * invoker, \fBSourceLineInfo\fP const & lineInfo, \fBStringRef\fP const & classOrMethod, \fBNameAndTags\fP const & nameAndTags)\fR [noexcept]\fP"

.SS "Catch::AutoReg::~AutoReg ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
