.TH "Catch::detail::is_range_impl< T, typename >" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::detail::is_range_impl< T, typename >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.PP
Inherits std::false_type\&.
.PP
Inherited by \fBCatch::is_range< T >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
