.TH "Catch::Decomposer" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Decomposer
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T> auto \fBoperator<=\fP (T const &lhs) \-> \fBExprLhs\fP< T const & >"
.br
.ti -1c
.RI "auto \fBoperator<=\fP (bool value) \-> \fBExprLhs\fP< bool >"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "auto Catch::Decomposer::operator<= (bool value) \-> \fBExprLhs\fP<bool> \fR [inline]\fP"

.SS "template<typename T> auto Catch::Decomposer::operator<= (T const & lhs) \-> \fBExprLhs\fP<T const&> \fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
