.TH "Catch::Generators::GeneratorWrapper< T >" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Generators::GeneratorWrapper< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeneratorWrapper\fP (std::unique_ptr< \fBIGenerator\fP< T > > generator)"
.br
.ti -1c
.RI "T const & \fBget\fP () const"
.br
.ti -1c
.RI "bool \fBnext\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBCatch::Generators::GeneratorWrapper\fP< T >::GeneratorWrapper (std::unique_ptr< \fBIGenerator\fP< T > > generator)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T> T const  & \fBCatch::Generators::GeneratorWrapper\fP< T >::get () const\fR [inline]\fP"

.SS "template<typename T> bool \fBCatch::Generators::GeneratorWrapper\fP< T >::next ()\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
