.TH "Catch::ShowDurations" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::ShowDurations
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBOrNot\fP { \fBDefaultForReporter\fP, \fBAlways\fP, \fBNever\fP }"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBCatch::ShowDurations::OrNot\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIDefaultForReporter \fP
.TP
\f(BIAlways \fP
.TP
\f(BINever \fP


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
