.TH "Catch::Matchers::Generic::PredicateMatcher< T >" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Matchers::Generic::PredicateMatcher< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.PP
Inherits \fBCatch::Matchers::Impl::MatcherBase< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPredicateMatcher\fP (std::function< bool(T const &)> const &elem, std::string const &descr)"
.br
.ti -1c
.RI "bool \fBmatch\fP (T const &item) const override"
.br
.ti -1c
.RI "std::string \fBdescribe\fP () const override"
.br
.in -1c

Public Member Functions inherited from \fBCatch::Matchers::Impl::MatcherBase< T >\fP
.in +1c
.ti -1c
.RI "\fBMatchAllOf\fP< T > \fBoperator&&\fP (\fBMatcherBase\fP const &other) const"
.br
.ti -1c
.RI "\fBMatchAnyOf\fP< T > \fBoperator||\fP (\fBMatcherBase\fP const &other) const"
.br
.ti -1c
.RI "\fBMatchNotOf\fP< T > \fBoperator!\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBCatch::Matchers::Impl::MatcherUntypedBase\fP
.in +1c
.ti -1c
.RI "\fBMatcherUntypedBase\fP ()=default"
.br
.ti -1c
.RI "\fBMatcherUntypedBase\fP (\fBMatcherUntypedBase\fP const &)=default"
.br
.ti -1c
.RI "\fBMatcherUntypedBase\fP & \fBoperator=\fP (\fBMatcherUntypedBase\fP const &)=delete"
.br
.ti -1c
.RI "std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBCatch::Matchers::Impl::MatcherUntypedBase\fP
.in +1c
.ti -1c
.RI "virtual \fB~MatcherUntypedBase\fP ()"
.br
.in -1c

Protected Attributes inherited from \fBCatch::Matchers::Impl::MatcherUntypedBase\fP
.in +1c
.ti -1c
.RI "std::string \fBm_cachedToString\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBCatch::Matchers::Generic::PredicateMatcher\fP< T >::PredicateMatcher (std::function< bool(T const &)> const & elem, std::string const & descr)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T> std::string \fBCatch::Matchers::Generic::PredicateMatcher\fP< T >::describe () const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBCatch::Matchers::Impl::MatcherUntypedBase\fP\&.
.SS "template<typename T> bool \fBCatch::Matchers::Generic::PredicateMatcher\fP< T >::match (T const & item) const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBCatch::Matchers::Impl::MatcherMethod< T >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
