.TH "Catch::IExceptionTranslator" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::IExceptionTranslator
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IExceptionTranslator\fP ()"
.br
.ti -1c
.RI "virtual std::string \fBtranslate\fP (ExceptionTranslators::const_iterator it, ExceptionTranslators::const_iterator itEnd) const =0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual Catch::IExceptionTranslator::~IExceptionTranslator ()\fR [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual std::string Catch::IExceptionTranslator::translate (ExceptionTranslators::const_iterator it, ExceptionTranslators::const_iterator itEnd) const\fR [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
