.TH "Catch::ITestInvoker" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::ITestInvoker
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.PP
Inherited by \fBCatch::TestInvokerAsMethod< C >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinvoke\fP () const =0"
.br
.ti -1c
.RI "virtual \fB~ITestInvoker\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual Catch::ITestInvoker::~ITestInvoker ()\fR [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void Catch::ITestInvoker::invoke () const\fR [pure virtual]\fP"

.PP
Implemented in \fBCatch::TestInvokerAsMethod< C >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
