.TH "Catch::StringMaker< wchar_t const * >" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::StringMaker< wchar_t const * >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBconvert\fP (wchar_t const *str)"
.br
.ti -1c
.RI "static std::enable_if<\fB::Catch::Detail::IsStreamInsertable\fP< Fake >::value, std::string >::type \fBconvert\fP (const Fake &value)"
.br
.ti -1c
.RI "static std::enable_if<!\fB::Catch::Detail::IsStreamInsertable\fP< Fake >::value, std::string >::type \fBconvert\fP (const Fake &value)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static std::enable_if<\fB::Catch::Detail::IsStreamInsertable\fP< Fake >::value, std::string >::type \fBCatch::StringMaker\fP< wchar_t const *, typename >::convert (const Fake & value)\fR [inline]\fP, \fR [static]\fP"

.SS "static std::enable_if<!\fB::Catch::Detail::IsStreamInsertable\fP< Fake >::value, std::string >::type \fBCatch::StringMaker\fP< wchar_t const *, typename >::convert (const Fake & value)\fR [inline]\fP, \fR [static]\fP"

.SS "static std::string \fBCatch::StringMaker\fP< wchar_t const * >::convert (wchar_t const * str)\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
