.TH "Catch::is_range< T >" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::is_range< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.PP
Inherits \fBCatch::detail::is_range_impl< T, typename >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
