.TH "Catch::WarnAbout" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::WarnAbout
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBWhat\fP { \fBNothing\fP = 0x00, \fBNoAssertions\fP = 0x01, \fBNoTests\fP = 0x02 }"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBCatch::WarnAbout::What\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BINothing \fP
.TP
\f(BINoAssertions \fP
.TP
\f(BINoTests \fP


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
