.TH "Catch::Matchers::Impl::MatcherMethod< ObjectT >" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Matchers::Impl::MatcherMethod< ObjectT >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.PP
Inherited by \fBCatch::Matchers::Impl::MatcherBase< std::string >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBmatch\fP (ObjectT const &arg) const =0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename ObjectT> virtual bool \fBCatch::Matchers::Impl::MatcherMethod\fP< ObjectT >::match (ObjectT const & arg) const\fR [pure virtual]\fP"

.PP
Implemented in \fBCatch::Matchers::Generic::PredicateMatcher< T >\fP, \fBCatch::Matchers::Impl::MatchAllOf< ArgT >\fP, \fBCatch::Matchers::Impl::MatchAnyOf< ArgT >\fP, and \fBCatch::Matchers::Impl::MatchNotOf< ArgT >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
