.TH "Catch::StreamEndStop" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::StreamEndStop
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBoperator+\fP () const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "std::string Catch::StreamEndStop::operator+ () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
