.TH "Catch::Generators::pf" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Generators::pf
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T, typename\&.\&.\&. Args> std::unique_ptr< T > \fBmake_unique\fP (Args &&\&.\&.\&. args)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename T, typename\&.\&.\&. Args> std::unique_ptr< T > Catch::Generators::pf::make_unique (Args &&\&.\&.\&. args)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
