.TH "Catch::NameAndTags" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::NameAndTags
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNameAndTags\fP (\fBStringRef\fP const &name_=\fBStringRef\fP(), \fBStringRef\fP const &tags_=\fBStringRef\fP()) noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBStringRef\fP \fBname\fP"
.br
.ti -1c
.RI "\fBStringRef\fP \fBtags\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::NameAndTags::NameAndTags (\fBStringRef\fP const & name_ = \fR\fBStringRef\fP()\fP, \fBStringRef\fP const & tags_ = \fR\fBStringRef\fP()\fP)\fR [noexcept]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBStringRef\fP Catch::NameAndTags::name"

.SS "\fBStringRef\fP Catch::NameAndTags::tags"


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
