.TH "Catch::IStream" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::IStream
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IStream\fP ()"
.br
.ti -1c
.RI "virtual std::ostream & \fBstream\fP () const =0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual Catch::IStream::~IStream ()\fR [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual std::ostream & Catch::IStream::stream () const\fR [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
