.TH "Catch::Matchers::Floating" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Matchers::Floating
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBWithinAbsMatcher\fP"
.br
.ti -1c
.RI "struct \fBWithinRelMatcher\fP"
.br
.ti -1c
.RI "struct \fBWithinUlpsMatcher\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
