.TH "Catch::SectionEndInfo" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::SectionEndInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSectionInfo\fP \fBsectionInfo\fP"
.br
.ti -1c
.RI "\fBCounts\fP \fBprevAssertions\fP"
.br
.ti -1c
.RI "double \fBdurationInSeconds\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "double Catch::SectionEndInfo::durationInSeconds"

.SS "\fBCounts\fP Catch::SectionEndInfo::prevAssertions"

.SS "\fBSectionInfo\fP Catch::SectionEndInfo::sectionInfo"


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
