.TH "Catch::ScopedMessage" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::ScopedMessage
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScopedMessage\fP (\fBMessageBuilder\fP const &builder)"
.br
.ti -1c
.RI "\fBScopedMessage\fP (\fBScopedMessage\fP &duplicate)=delete"
.br
.ti -1c
.RI "\fBScopedMessage\fP (\fBScopedMessage\fP &&old)"
.br
.ti -1c
.RI "\fB~ScopedMessage\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMessageInfo\fP \fBm_info\fP"
.br
.ti -1c
.RI "bool \fBm_moved\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::ScopedMessage::ScopedMessage (\fBMessageBuilder\fP const & builder)\fR [explicit]\fP"

.SS "Catch::ScopedMessage::ScopedMessage (\fBScopedMessage\fP & duplicate)\fR [delete]\fP"

.SS "Catch::ScopedMessage::ScopedMessage (\fBScopedMessage\fP && old)"

.SS "Catch::ScopedMessage::~ScopedMessage ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBMessageInfo\fP Catch::ScopedMessage::m_info"

.SS "bool Catch::ScopedMessage::m_moved"


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
