.TH "Catch::GeneratorException" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::GeneratorException
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.PP
Inherits std::exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeneratorException\fP (const char *msg)"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const noexcept override final"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::GeneratorException::GeneratorException (const char * msg)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const char * Catch::GeneratorException::what () const\fR [final]\fP, \fR [override]\fP, \fR [noexcept]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
