.TH "Catch::UseColour" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::UseColour
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBYesOrNo\fP { \fBAuto\fP, \fBYes\fP, \fBNo\fP }"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBCatch::UseColour::YesOrNo\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIAuto \fP
.TP
\f(BIYes \fP
.TP
\f(BINo \fP


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
