.TH "Catch::ITestCaseRegistry" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::ITestCaseRegistry
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ITestCaseRegistry\fP ()"
.br
.ti -1c
.RI "virtual std::vector< \fBTestCase\fP > const & \fBgetAllTests\fP () const =0"
.br
.ti -1c
.RI "virtual std::vector< \fBTestCase\fP > const & \fBgetAllTestsSorted\fP (\fBIConfig\fP const &config) const =0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual Catch::ITestCaseRegistry::~ITestCaseRegistry ()\fR [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual std::vector< \fBTestCase\fP > const  & Catch::ITestCaseRegistry::getAllTests () const\fR [pure virtual]\fP"

.SS "virtual std::vector< \fBTestCase\fP > const  & Catch::ITestCaseRegistry::getAllTestsSorted (\fBIConfig\fP const & config) const\fR [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
