.TH "Catch::Timer" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Timer
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "auto \fBgetElapsedNanoseconds\fP () const \-> uint64_t"
.br
.ti -1c
.RI "auto \fBgetElapsedMicroseconds\fP () const \-> uint64_t"
.br
.ti -1c
.RI "auto \fBgetElapsedMilliseconds\fP () const \-> unsigned int"
.br
.ti -1c
.RI "auto \fBgetElapsedSeconds\fP () const \-> double"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "auto Catch::Timer::getElapsedMicroseconds () const \->  uint64_t"

.SS "auto Catch::Timer::getElapsedMilliseconds () const \->  unsigned int"

.SS "auto Catch::Timer::getElapsedNanoseconds () const \->  uint64_t"

.SS "auto Catch::Timer::getElapsedSeconds () const \->  double"

.SS "void Catch::Timer::start ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
