.TH "Catch::Matchers::StdString" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Matchers::StdString
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCasedString\fP"
.br
.ti -1c
.RI "struct \fBContainsMatcher\fP"
.br
.ti -1c
.RI "struct \fBEndsWithMatcher\fP"
.br
.ti -1c
.RI "struct \fBEqualsMatcher\fP"
.br
.ti -1c
.RI "struct \fBRegexMatcher\fP"
.br
.ti -1c
.RI "struct \fBStartsWithMatcher\fP"
.br
.ti -1c
.RI "struct \fBStringMatcherBase\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
