.TH "Catch::detail::is_range_impl< T, typename void_type< decltype(begin(std::declval< T >()))>::type >" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::detail::is_range_impl< T, typename void_type< decltype(begin(std::declval< T >()))>::type >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.PP
Inherits std::false_type, and std::true_type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
