.TH "Catch::literals" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::literals
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDetail::Approx\fP \fBoperator''_a\fP (long double val)"
.br
.ti -1c
.RI "\fBDetail::Approx\fP \fBoperator''_a\fP (unsigned long long val)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBDetail::Approx\fP Catch::literals::operator''_a (long double val)"

.SS "\fBDetail::Approx\fP Catch::literals::operator''_a (unsigned long long val)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
