.TH "Catch::Matchers::Exception" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Matchers::Exception
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExceptionMessageMatcher\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
