.TH "Catch::IExceptionTranslatorRegistry" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::IExceptionTranslatorRegistry
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IExceptionTranslatorRegistry\fP ()"
.br
.ti -1c
.RI "virtual std::string \fBtranslateActiveException\fP () const =0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual Catch::IExceptionTranslatorRegistry::~IExceptionTranslatorRegistry ()\fR [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual std::string Catch::IExceptionTranslatorRegistry::translateActiveException () const\fR [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
