.TH "Catch::SectionInfo" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::SectionInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSectionInfo\fP (\fBSourceLineInfo\fP const &_lineInfo, std::string const &_name)"
.br
.ti -1c
.RI "\fBSectionInfo\fP (\fBSourceLineInfo\fP const &_lineInfo, std::string const &_name, std::string const &)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "std::string \fBdescription\fP"
.br
.ti -1c
.RI "\fBSourceLineInfo\fP \fBlineInfo\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::SectionInfo::SectionInfo (\fBSourceLineInfo\fP const & _lineInfo, std::string const & _name)"

.SS "Catch::SectionInfo::SectionInfo (\fBSourceLineInfo\fP const & _lineInfo, std::string const & _name, std::string const & )\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string Catch::SectionInfo::description"

.SS "\fBSourceLineInfo\fP Catch::SectionInfo::lineInfo"

.SS "std::string Catch::SectionInfo::name"


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
