.TH "Catch::AssertionInfo" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::AssertionInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBStringRef\fP \fBmacroName\fP"
.br
.ti -1c
.RI "\fBSourceLineInfo\fP \fBlineInfo\fP"
.br
.ti -1c
.RI "\fBStringRef\fP \fBcapturedExpression\fP"
.br
.ti -1c
.RI "\fBResultDisposition::Flags\fP \fBresultDisposition\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBStringRef\fP Catch::AssertionInfo::capturedExpression"

.SS "\fBSourceLineInfo\fP Catch::AssertionInfo::lineInfo"

.SS "\fBStringRef\fP Catch::AssertionInfo::macroName"

.SS "\fBResultDisposition::Flags\fP Catch::AssertionInfo::resultDisposition"


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
