.TH "Catch::Matchers::Vector" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Matchers::Vector
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBApproxMatcher\fP"
.br
.ti -1c
.RI "struct \fBContainsElementMatcher\fP"
.br
.ti -1c
.RI "struct \fBContainsMatcher\fP"
.br
.ti -1c
.RI "struct \fBEqualsMatcher\fP"
.br
.ti -1c
.RI "struct \fBUnorderedEqualsMatcher\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
