.TH "Catch::WaitForKeypress" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::WaitForKeypress
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBWhen\fP { \fBNever\fP, \fBBeforeStart\fP = 1, \fBBeforeExit\fP = 2, \fBBeforeStartAndExit\fP = BeforeStart | BeforeExit }"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBCatch::WaitForKeypress::When\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BINever \fP
.TP
\f(BIBeforeStart \fP
.TP
\f(BIBeforeExit \fP
.TP
\f(BIBeforeStartAndExit \fP


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
