.TH "Catch::detail" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::detail
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBis_range_impl\fP"
.br
.ti -1c
.RI "struct \fBis_range_impl< T, typename void_type< decltype(begin(std::declval< T >()))>::type >\fP"
.br
.ti -1c
.RI "struct \fBvoid_type\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
