.TH "Catch::MessageStream" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::MessageStream
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.PP
Inherited by \fBCatch::MessageBuilder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T> \fBMessageStream\fP & \fBoperator<<\fP (T const &value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBReusableStringStream\fP \fBm_stream\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> \fBMessageStream\fP & Catch::MessageStream::operator<< (T const & value)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBReusableStringStream\fP Catch::MessageStream::m_stream"


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
