.TH "Catch::detail::void_type<... >" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::detail::void_type<... >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtype\fP = void"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename\&.\&.\&.> using \fBCatch::detail::void_type\fP<\&.\&.\&. >::type = void"


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
