.TH "Catch::Detail::EnumInfo" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Detail::EnumInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~EnumInfo\fP ()"
.br
.ti -1c
.RI "\fBStringRef\fP \fBlookup\fP (int value) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBStringRef\fP \fBm_name\fP"
.br
.ti -1c
.RI "std::vector< std::pair< int, \fBStringRef\fP > > \fBm_values\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::Detail::EnumInfo::~EnumInfo ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBStringRef\fP Catch::Detail::EnumInfo::lookup (int value) const"

.SH "Member Data Documentation"
.PP 
.SS "\fBStringRef\fP Catch::Detail::EnumInfo::m_name"

.SS "std::vector<std::pair<int, \fBStringRef\fP> > Catch::Detail::EnumInfo::m_values"


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
