.TH "v1.5/funkcijos.h" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
v1.5/funkcijos.h
.SH SYNOPSIS
.br
.PP
\fR#include 'mano_lib\&.h'\fP
.br
\fR#include '\&.\&./Vector\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBZmogus\fP"
.br
.ti -1c
.RI "class \fBStudentas\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBGeneruotiPazymius\fP (int pazymiuSk, \fBVector\fP< int > &pazymiai)"
.br
.ti -1c
.RI "float \fBVidurkis\fP (\fBVector\fP< int > pazymiai)"
.br
.ti -1c
.RI "float \fBMediana\fP (\fBVector\fP< int > pazymiai)"
.br
.ti -1c
.RI "template<typename Container> void \fBGeneruotiStudentus\fP (int studentuSk, Container &studentai)"
.br
.ti -1c
.RI "template<typename Container> void \fBNuskaitytiStudentusIsFailo\fP (string failas, Container &studentai)"
.br
.ti -1c
.RI "template<typename Container> void \fBRikiuotiStudentus\fP (Container &studentai, int pasirinkimas)"
.br
.ti -1c
.RI "template<typename Container> void \fBSkaiciuotiGalutini\fP (Container &studentai, bool vid)"
.br
.ti -1c
.RI "template<typename Container> void \fBStudentuAtskirimas\fP (Container &studentai)"
.br
.ti -1c
.RI "template<typename Container> void \fBSkaidytiStudentus3Strategija\fP (Container &studentai)"
.br
.ti -1c
.RI "void \fBFailuGeneravimas\fP (int studentuSk, int pazymiuSk)"
.br
.ti -1c
.RI "void \fBTest1\fP ()"
.br
.ti -1c
.RI "void \fBTest2\fP ()"
.br
.ti -1c
.RI "void \fBTest3\fP ()"
.br
.ti -1c
.RI "void \fBTestStudentas\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void FailuGeneravimas (int studentuSk, int pazymiuSk)"

.SS "void GeneruotiPazymius (int pazymiuSk, \fBVector\fP< int > & pazymiai)"

.SS "template<typename Container> void GeneruotiStudentus (int studentuSk, Container & studentai)"

.SS "float Mediana (\fBVector\fP< int > pazymiai)"

.SS "template<typename Container> void NuskaitytiStudentusIsFailo (string failas, Container & studentai)"

.SS "template<typename Container> void RikiuotiStudentus (Container & studentai, int pasirinkimas)"

.SS "template<typename Container> void SkaiciuotiGalutini (Container & studentai, bool vid)"

.SS "template<typename Container> void SkaidytiStudentus3Strategija (Container & studentai)"

.SS "template<typename Container> void StudentuAtskirimas (Container & studentai)"

.SS "void Test1 ()"

.SS "void Test2 ()"

.SS "void Test3 ()"

.SS "void TestStudentas ()"

.SS "float Vidurkis (\fBVector\fP< int > pazymiai)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
