.TH "v1.5/funkcijos.cpp" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
v1.5/funkcijos.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'funkcijos\&.h'\fP
.br
\fR#include '\&.\&./Vector\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBVidurkis\fP (\fBVector\fP< int > pazymiai)"
.br
.ti -1c
.RI "float \fBMediana\fP (\fBVector\fP< int > pazymiai)"
.br
.ti -1c
.RI "void \fBGeneruotiPazymius\fP (int pazymiuSk, \fBVector\fP< int > &pazymiai)"
.br
.ti -1c
.RI "void \fBFailuGeneravimas\fP (int studentuSk, int pazymiuSk)"
.br
.ti -1c
.RI "void \fBTest1\fP ()"
.br
.ti -1c
.RI "void \fBTest2\fP ()"
.br
.ti -1c
.RI "void \fBTest3\fP ()"
.br
.ti -1c
.RI "void \fBTestStudentas\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void FailuGeneravimas (int studentuSk, int pazymiuSk)"

.SS "void GeneruotiPazymius (int pazymiuSk, \fBVector\fP< int > & pazymiai)"

.SS "float Mediana (\fBVector\fP< int > pazymiai)"

.SS "void Test1 ()"

.SS "void Test2 ()"

.SS "void Test3 ()"

.SS "void TestStudentas ()"

.SS "float Vidurkis (\fBVector\fP< int > pazymiai)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
