.TH "v1.5/main.cpp" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
v1.5/main.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'mano_lib\&.h'\fP
.br
\fR#include 'funkcijos\&.h'\fP
.br
\fR#include '\&.\&./Vector\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
