.TH "v1.5/vectors_testing/test.cpp" 3 "Version v3.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
v1.5/vectors_testing/test.cpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./Vector\&.h'\fP
.br
\fR#include '\&.\&./mano_lib\&.h'\fP
.br
\fR#include '\&.\&./funkcijos\&.cpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBFailTest\fP ()"
.br
.ti -1c
.RI "template<typename V> int \fBcount_reallocations\fP (V &vec, size_t N)"
.br
.ti -1c
.RI "\fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename V> int count_reallocations (V & vec, size_t N)"

.SS "void FailTest ()"

.SS "main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
